### ISSUE TITLE
Bleeding when out of water or food

### ISSUE THREAD

**Issue by KRDucky** [AgentRev/ACE3Wasteland.Altis#4]
When you are out of water or food and are taking damage, you start bleeding from every body part. After you drink or eat you have to bandage all your body parts to stop the bleeding. It would be ideal if there was an option to disable the survival system.

**Comment by AgentRev** [comment]
Fixed https://github.com/AgentRev/ACE3Wasteland.Altis/commit/e1bdc5d61ca709328d74b3f55065553d7bc75594
